onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - esbuild
  - node
  - sharp
  - simple-git-hooks
  - unrs-resolver

patchedDependencies:
  next: patches/next.patch

# https://pnpm.io/settings#shellemulator
shellEmulator: true

# https://pnpm.io/settings#strictdepbuilds
strictDepBuilds: true
