onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - node
  - sharp
  - simple-git-hooks
  - unrs-resolver

patchedDependencies:
  next: patches/next.patch

shellEmulator: true

strictDepBuilds: true
