onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
  - simple-git-hooks
  - typesense-instantsearch-adapter
  - unrs-resolver

shellEmulator: true

strictDepBuilds: true

# Incorrect peer deps in `@keystar/ui` package.
overrides:
  "@types/react": "$@types/react"
  "@types/react-dom": "$@types/react-dom"
