allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  core-js: false
  esbuild: true
  sharp: true
  simple-git-hooks: true
  typesense-instantsearch-adapter: false
  unrs-resolver: false

minimumReleaseAge: 1440

patchedDependencies:
  next: patches/next.patch

shellEmulator: true

strictDepBuilds: true
