allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  better-sqlite3: false
  esbuild: true
  lefthook: true
  msgpackr-extract: false

autoDedupe: true

engineStrict: true

minimumReleaseAge: 240

patchedDependencies:
  '@react-aria/optimize-locales-plugin': patches/@react-aria__optimize-locales-plugin.patch
  next: patches/next.patch

saveTypes: true

shellEmulator: true
