import { fileURLToPath } from "node:url";

import nextEnv from "@next/env";
import * as v from "valibot";

import { client, scripts } from "#/configs/env.schema.ts";

const projectDir = fileURLToPath(new URL("../..", import.meta.url));

/**
 * These scripts manage collections and api keys, so they need the typesense admin api key, which is not part of the
 * app's environment. We therefore only validate the values these scripts actually need, instead of the app's full
 * environment.
 *
 * `NEXT_PUBLIC_TYPESENSE_SEARCH_API_KEY` is intentionally not validated: it is generated by these scripts.
 */
const { combinedEnv } = nextEnv.loadEnvConfig(projectDir);
export const env = v.parse(
	v.object({
		NEXT_PUBLIC_TYPESENSE_COLLECTION_NAME_RESOURCES: client.entries.NEXT_PUBLIC_TYPESENSE_COLLECTION_NAME_RESOURCES,
		NEXT_PUBLIC_TYPESENSE_COLLECTION_NAME_WEBSITE: client.entries.NEXT_PUBLIC_TYPESENSE_COLLECTION_NAME_WEBSITE,
		NEXT_PUBLIC_TYPESENSE_HOST: client.entries.NEXT_PUBLIC_TYPESENSE_HOST,
		NEXT_PUBLIC_TYPESENSE_PORT: client.entries.NEXT_PUBLIC_TYPESENSE_PORT,
		NEXT_PUBLIC_TYPESENSE_PROTOCOL: client.entries.NEXT_PUBLIC_TYPESENSE_PROTOCOL,
		TYPESENSE_ADMIN_API_KEY: scripts.entries.TYPESENSE_ADMIN_API_KEY,
	}),
	combinedEnv,
);
