/**
 * Emits the api client from an OpenAPI 3.1 document. The document is validated with redocly before it gets here, so
 * this module assumes structural validity - `$ref`s resolve, every operation has a unique `operationId`, path
 * parameters are declared - and throws on anything it does not support, instead of guessing.
 *
 * Two modules are emitted: `schemas.ts` with a named type per `components.schemas` entry - plus the `CacheTag` enum as
 * a runtime array, so the revalidation webhook can validate its payload against the vocabulary - and `endpoints.ts`
 * with one endpoint object per operation, plus a same-named namespace holding the operation's `Params`, `SearchParams`,
 * `Body` and `Response` types. The generic machinery lives in `#/lib/api/endpoint.ts`; the generated output is data
 * only.
 */

import { assert } from "@acdh-oeaw/lib";

type JsonValue = string | number | boolean | null | Array<JsonValue> | { [key: string]: JsonValue };

/** The subset of JSON Schema 2020-12 which the emitter understands. */
export interface Schema {
	$ref?: string;
	additionalProperties?: Schema | boolean;
	allOf?: Array<Schema>;
	anyOf?: Array<Schema>;
	const?: JsonValue;
	default?: JsonValue;
	deprecated?: boolean;
	description?: string;
	enum?: Array<JsonValue>;
	format?: string;
	items?: Schema;
	maximum?: number;
	minimum?: number;
	oneOf?: Array<Schema>;
	prefixItems?: Array<Schema>;
	properties?: Record<string, Schema>;
	required?: Array<string>;
	type?: SchemaType | Array<SchemaType>;
}

type SchemaType = "array" | "boolean" | "integer" | "null" | "number" | "object" | "string";

export interface Parameter {
	description?: string;
	in: "cookie" | "header" | "path" | "query";
	name: string;
	required?: boolean;
	schema: Schema;
}

type MediaTypes = Record<string, { schema?: Schema }>;

export interface Operation {
	deprecated?: boolean;
	description?: string;
	operationId: string;
	parameters?: Array<Parameter | { $ref: string }>;
	requestBody?: { content: MediaTypes; required?: boolean };
	responses: Record<string, { content?: MediaTypes; description?: string }>;
	summary?: string;
	"x-cache-tags"?: Array<string>;
}

export const httpMethods = ["delete", "get", "head", "options", "patch", "post", "put", "trace"] as const;

export type HttpMethod = (typeof httpMethods)[number];

export interface Document {
	components?: {
		parameters?: Record<string, Parameter>;
		schemas?: Record<string, Schema>;
	};
	paths: Record<string, Partial<Record<HttpMethod, Operation>>>;
}

export interface EmitOptions {
	/** Module specifier of the runtime helper which turns an endpoint definition into an endpoint object. */
	endpointModule: string;
	/** Module specifier the endpoints module imports the schema types from. */
	schemasModule: string;
}

export interface EmitResult {
	endpoints: string;
	schemas: string;
}

const header = "/** This file was generated by `scripts/openapi/generate.ts`. Do not edit it by hand. */\n\n";

const identifierPattern = /^[$_\p{ID_Start}][$\p{ID_Continue}]*$/u;

function isIdentifier(value: string): boolean {
	return identifierPattern.test(value);
}

function propertyKey(name: string): string {
	return isIdentifier(name) ? name : JSON.stringify(name);
}

function literal(value: JsonValue): string {
	return JSON.stringify(value);
}

function indent(code: string, depth: number): string {
	const prefix = "\t".repeat(depth);
	return code
		.split("\n")
		.map((line) => (line.length > 0 ? prefix + line : line))
		.join("\n");
}

function docComment(schema: Pick<Schema, "default" | "deprecated" | "description" | "maximum" | "minimum">): string {
	const lines: Array<string> = [];

	if (schema.description != null && schema.description.length > 0) {
		lines.push(...schema.description.trim().split("\n"));
	}

	/** Ranges cannot be expressed in the type, so they are at least visible on hover. */
	const tags: Array<string> = [];
	if (schema.default !== undefined) {
		tags.push(`@default ${literal(schema.default)}`);
	}
	if (schema.minimum !== undefined) {
		tags.push(`@minimum ${String(schema.minimum)}`);
	}
	if (schema.maximum !== undefined) {
		tags.push(`@maximum ${String(schema.maximum)}`);
	}
	if (tags.length > 0) {
		if (lines.length > 0) {
			lines.push("");
		}
		lines.push(...tags);
	}

	if (schema.deprecated === true) {
		if (lines.length > 0) {
			lines.push("");
		}
		lines.push("@deprecated");
	}

	if (lines.length === 0) {
		return "";
	}

	/** A description could contain the sequence which closes a block comment. */
	const safe = lines.map((line) => line.replaceAll("*/", "*\\/"));

	if (safe.length === 1) {
		return `/** ${safe[0]!} */\n`;
	}

	return `/**\n${safe.map((line) => (line.length > 0 ? ` * ${line}` : " *")).join("\n")}\n */\n`;
}

function refName(ref: string): string {
	const prefix = "#/components/schemas/";
	assert(ref.startsWith(prefix), `Unsupported reference "${ref}", only "${prefix}" references are supported.`);
	const name = ref.slice(prefix.length);
	assert(isIdentifier(name), `Schema name "${name}" is not a valid identifier.`);
	return name;
}

/**
 * Splits a rendered type at its top-level `|` separators, so nested unions can be flattened - `anyOf: [{anyOf: [A,
 * null]}, null]` must not render a duplicate `null`.
 */
function splitUnion(type: string): Array<string> {
	const members: Array<string> = [];
	let depth = 0;
	let start = 0;
	let index = 0;

	while (index < type.length) {
		const char = type[index]!;

		if (char === '"') {
			/** Skip a string literal, which may contain separators or brackets. */
			index += 1;
			while (index < type.length && type[index] !== '"') {
				if (type[index] === "\\") {
					index += 1;
				}
				index += 1;
			}
		} else if ("{[(<".includes(char)) {
			depth += 1;
		} else if ("}])>".includes(char)) {
			depth -= 1;
		} else if (char === "|" && depth === 0) {
			members.push(type.slice(start, index).trim());
			start = index + 1;
		}

		index += 1;
	}

	members.push(type.slice(start).trim());

	return members.filter((member) => member.length > 0);
}

function union(members: Array<string>): string {
	const unique = [...new Set(members.flatMap((member) => splitUnion(member)))];
	if (unique.includes("unknown")) {
		return "unknown";
	}
	if (unique.length === 0) {
		return "never";
	}
	return unique.join(" | ");
}

/** Renders an object schema as a type literal body, i.e. without the surrounding braces. */
function objectMembers(schema: Schema, schemas: string): string {
	const required = new Set(schema.required ?? []);
	const members: Array<string> = [];

	for (const [name, property] of Object.entries(schema.properties ?? {})) {
		const optional = required.has(name) ? "" : "?";
		members.push(`${docComment(property)}${propertyKey(name)}${optional}: ${toType(property, schemas)};`);
	}

	return members.join("\n");
}

function isObjectSchema(schema: Schema): boolean {
	return schema.type === "object" || schema.properties != null;
}

/**
 * An object schema with named properties, and no index signature, is rendered as an `interface` at declaration sites.
 * Everything else is a `type` alias.
 */
function isInterfaceLike(schema: Schema): boolean {
	return (
		isObjectSchema(schema) &&
		schema.properties != null &&
		(schema.additionalProperties == null || schema.additionalProperties === false) &&
		schema.allOf == null &&
		schema.anyOf == null &&
		schema.oneOf == null &&
		schema.$ref == null &&
		!Array.isArray(schema.type)
	);
}

function objectType(schema: Schema, schemas: string): string {
	const members = objectMembers(schema, schemas);
	const additional = schema.additionalProperties;
	const record =
		additional === true || (additional != null && additional !== false)
			? `Record<string, ${additional === true ? "unknown" : toType(additional, schemas)}>`
			: null;

	if (members.length === 0) {
		return record ?? "Record<string, never>";
	}

	const body = `{\n${indent(members, 1)}\n}`;

	return record != null ? `(${body} & ${record})` : body;
}

function scalarType(type: SchemaType, schema: Schema, schemas: string): string {
	switch (type) {
		case "array": {
			if (schema.prefixItems != null) {
				const items = schema.prefixItems.map((item) => toType(item, schemas));
				const rest = schema.items != null ? `, ...Array<${toType(schema.items, schemas)}>` : "";
				return `[${items.join(", ")}${rest}]`;
			}
			return `Array<${schema.items != null ? toType(schema.items, schemas) : "unknown"}>`;
		}
		case "boolean": {
			return "boolean";
		}
		case "integer":
		case "number": {
			return "number";
		}
		case "null": {
			return "null";
		}
		case "object": {
			return objectType(schema, schemas);
		}
		case "string": {
			return "string";
		}
	}
}

/** `schemas` is the namespace prefix for referenced schema types, empty inside the schemas module itself. */
export function toType(schema: Schema, schemas = ""): string {
	if (schema.$ref != null) {
		return schemas + refName(schema.$ref);
	}

	if (schema.const !== undefined) {
		return literal(schema.const);
	}

	if (schema.enum != null) {
		return union(schema.enum.map((value) => literal(value)));
	}

	const parts: Array<string> = [];

	if (schema.allOf != null) {
		parts.push(schema.allOf.map((member) => toType(member, schemas)).join(" & "));
	}

	if (schema.anyOf != null) {
		parts.push(union(schema.anyOf.map((member) => toType(member, schemas))));
	}

	if (schema.oneOf != null) {
		parts.push(union(schema.oneOf.map((member) => toType(member, schemas))));
	}

	if (schema.type != null) {
		const types = Array.isArray(schema.type) ? schema.type : [schema.type];
		parts.push(union(types.map((type) => scalarType(type, schema, schemas))));
	} else if (schema.properties != null) {
		parts.push(objectType(schema, schemas));
	}

	if (parts.length === 0) {
		/** An empty schema matches any value. */
		return "unknown";
	}

	return parts.length === 1 ? parts[0]! : parts.map((part) => `(${part})`).join(" & ");
}

function declaration(name: string, schema: Schema, schemas: string, exported = true): string {
	const prefix = exported ? "export " : "";

	if (isInterfaceLike(schema)) {
		const members = objectMembers(schema, schemas);
		const body = members.length === 0 ? "" : `\n${indent(members, 1)}\n`;
		return `${docComment(schema)}${prefix}interface ${name} {${body}}`;
	}

	return `${docComment(schema)}${prefix}type ${name} = ${toType(schema, schemas)};`;
}

function cacheTagValues(document: Document): ReadonlySet<string> {
	const schema = document.components?.schemas?.CacheTag;
	assert(schema?.enum != null, 'The document must declare a "CacheTag" enum schema.');
	return new Set(schema.enum.filter((value) => typeof value === "string"));
}

function emitSchemas(document: Document): string {
	const entries = Object.entries(document.components?.schemas ?? {});

	const declarations = entries.map(([name, schema]) => {
		assert(isIdentifier(name), `Schema name "${name}" is not a valid identifier.`);
		return declaration(name, schema, "");
	});

	const cacheTags = [...cacheTagValues(document)].map((tag) => literal(tag));

	declarations.push(
		`/** The \`CacheTag\` vocabulary as a value, for validating a revalidation webhook payload. */\nexport const cacheTags: ReadonlyArray<CacheTag> = [${cacheTags.join(", ")}];`,
	);

	return `${header}${declarations.join("\n\n")}\n`;
}

function resolveParameter(document: Document, parameter: Parameter | { $ref: string }): Parameter {
	if (!("$ref" in parameter)) {
		return parameter;
	}

	const prefix = "#/components/parameters/";
	assert(parameter.$ref.startsWith(prefix), `Unsupported parameter reference "${parameter.$ref}".`);
	const resolved = document.components?.parameters?.[parameter.$ref.slice(prefix.length)];
	assert(resolved != null, `Unresolved parameter reference "${parameter.$ref}".`);
	return resolved;
}

function parametersSchema(parameters: Array<Parameter>): Schema {
	const properties: Record<string, Schema> = {};
	const required: Array<string> = [];

	for (const parameter of parameters) {
		properties[parameter.name] = { description: parameter.description, ...parameter.schema };
		if (parameter.required === true) {
			required.push(parameter.name);
		}
	}

	return { type: "object", properties, required };
}

const jsonMediaType = "application/json";

interface SuccessResponse {
	/** `null` when the success response has no json body. */
	schema: Schema | null;
}

function successResponse(operation: Operation): SuccessResponse {
	const success = Object.entries(operation.responses)
		.filter(([status]) => status.startsWith("2") || status.startsWith("3"))
		.toSorted(([a], [b]) => a.localeCompare(b));

	assert(success.length > 0, `Operation "${operation.operationId}" declares no success response.`);

	const [, response] = success[0]!;
	const json = response.content?.[jsonMediaType];

	return { schema: json?.schema ?? null };
}

function pathParameterNames(pathname: string): Array<string> {
	return [...pathname.matchAll(/\{(?<name>[^}]+)\}/g)].map((match) => match.groups!.name!);
}

function emitEndpoint(
	document: Document,
	method: HttpMethod,
	pathname: string,
	operation: Operation,
	cacheTags: ReadonlySet<string>,
): string {
	const name = operation.operationId;
	assert(isIdentifier(name), `Operation id "${name}" is not a valid identifier.`);

	const parameters = (operation.parameters ?? []).map((parameter) => resolveParameter(document, parameter));
	const pathParameters = parameters.filter((parameter) => parameter.in === "path");
	const queryParameters = parameters.filter((parameter) => parameter.in === "query");
	const unsupported = parameters.filter((parameter) => parameter.in !== "path" && parameter.in !== "query");
	assert(
		unsupported.length === 0,
		`Operation "${name}" has unsupported ${unsupported.map((p) => `${p.in} parameter "${p.name}"`).join(", ")}.`,
	);

	const declared = new Set(pathParameters.map((parameter) => parameter.name));
	for (const parameter of pathParameterNames(pathname)) {
		assert(declared.has(parameter), `Operation "${name}" does not declare path parameter "${parameter}".`);
	}

	const tags = operation["x-cache-tags"] ?? [];
	for (const tag of tags) {
		assert(cacheTags.has(tag), `Operation "${name}" lists unknown cache tag "${tag}".`);
	}

	const members: Array<string> = [];
	const generics: Array<string> = [];

	if (pathParameters.length > 0) {
		members.push(declaration("Params", parametersSchema(pathParameters), "schemas."));
		generics.push(`params: ${name}.Params`);
	}

	if (queryParameters.length > 0) {
		members.push(declaration("SearchParams", parametersSchema(queryParameters), "schemas."));
		generics.push(`searchParams: ${name}.SearchParams`);
	}

	if (operation.requestBody != null) {
		const json = operation.requestBody.content[jsonMediaType];
		assert(json?.schema != null, `Operation "${name}" has a request body which is not "${jsonMediaType}".`);
		members.push(declaration("Body", json.schema, "schemas."));
		generics.push(`body: ${name}.Body`);
	}

	const response = successResponse(operation);
	const responseType = response.schema != null ? "json" : "response";

	if (response.schema != null) {
		members.push(declaration("Response", response.schema, "schemas."));
	} else {
		members.push("/** The success response has no json body, so the raw response is returned. */");
		members.push("export type Response = globalThis.Response;");
	}
	generics.push(`response: ${name}.Response`);

	const doc = docComment({
		deprecated: operation.deprecated,
		description: [operation.summary, operation.description].filter((part) => part != null).join("\n\n"),
	});

	const namespace = `${doc}export declare namespace ${name} {\n${indent(members.join("\n\n"), 1)}\n}`;

	const definition = [
		`method: ${literal(method)}`,
		`pathname: ${literal(pathname)}`,
		`cacheTags: [${tags.map((tag) => literal(tag)).join(", ")}]`,
		`responseType: ${literal(responseType)}`,
	];

	const endpoint = `export const ${name} = defineEndpoint<{ ${generics.join("; ")} }>({\n${indent(definition.join(",\n"), 1)},\n});`;

	return `${namespace}\n\n${endpoint}`;
}

/**
 * The cap every paginated list operation places on its `limit` query parameter. Emitted as a runtime constant, so a
 * consumer walking all pages of a list does not have to hard-code it.
 */
function maxPageSize(document: Document): number | null {
	const caps = new Set<number>();

	for (const item of Object.values(document.paths)) {
		for (const method of httpMethods) {
			for (const parameter of item[method]?.parameters ?? []) {
				const resolved = resolveParameter(document, parameter);
				if (resolved.in === "query" && resolved.name === "limit" && resolved.schema.maximum != null) {
					caps.add(resolved.schema.maximum);
				}
			}
		}
	}

	assert(caps.size <= 1, `Operations disagree on the maximum "limit": ${[...caps].join(", ")}.`);

	return caps.values().next().value ?? null;
}

function emitEndpoints(document: Document, options: EmitOptions): string {
	const cacheTags = cacheTagValues(document);
	const declarations: Array<string> = [];
	const operationIds = new Set<string>();

	const pageSize = maxPageSize(document);
	if (pageSize != null) {
		declarations.push(
			`/** The largest \`limit\` a paginated list operation accepts. */\nexport const maxPageSize = ${String(pageSize)};`,
		);
	}

	for (const [pathname, item] of Object.entries(document.paths)) {
		for (const method of httpMethods) {
			const operation = item[method];
			if (operation == null) {
				continue;
			}

			assert(!operationIds.has(operation.operationId), `Duplicate operation id "${operation.operationId}".`);
			operationIds.add(operation.operationId);

			declarations.push(emitEndpoint(document, method, pathname, operation, cacheTags));
		}
	}

	const imports = [
		`import { defineEndpoint } from ${literal(options.endpointModule)};`,
		`import type * as schemas from ${literal(options.schemasModule)};`,
	];

	return `${header}${imports.join("\n")}\n\n${declarations.join("\n\n")}\n`;
}

export function emit(document: Document, options: EmitOptions): EmitResult {
	return {
		endpoints: emitEndpoints(document, options),
		schemas: emitSchemas(document),
	};
}
