"use client";

import "#/app/(app)/(default)/network/members-and-partners/_components/members-and-partners-map.css";

import type { FeatureCollection, MultiPolygon, Polygon } from "geojson";
import type { LeafletEvent, Map as LeafletMap, LeafletMouseEvent, Path } from "leaflet";
import { useExtracted as useTranslations } from "next-intl";
import { type ReactNode, useEffect, useEffectEvent, useRef, useState } from "react";

import { Select } from "#/components/ui/select.tsx";
import type { MemberOrPartnerListItem } from "#/lib/api/schemas.ts";
import { href } from "#/lib/navigation/href.ts";
import { Link } from "#/lib/navigation/link.tsx";
import { type Router, useRouter } from "#/lib/navigation/router.ts";

type PrefetchKind = NonNullable<NonNullable<Parameters<Router["prefetch"]>[1]>["kind"]>;

/**
 * `PrefetchKind.FULL`, the `kind` of a `router.prefetch` which loads the page rather than only its route's App Shell.
 * Next does not export the enum from a public module, so its type is read off `router.prefetch` and its value written
 * out.
 */
const fullPrefetch = "full" as PrefetchKind;

/** Generated by `scripts/geo/generate.sh`, which documents how the outlines are simplified. */
const countriesPathname = "/geo/countries.json";

/** A country's outline, with only what the map needs from the Natural Earth properties. */
interface CountryProperties {
	/** The country's names in Natural Earth - short, long, and official - to match a member or partner's name against. */
	names: Array<string>;
}

type Countries = FeatureCollection<Polygon | MultiPolygon, CountryProperties>;

type Status = MemberOrPartnerListItem["status"];

const statuses: ReadonlyArray<Status> = ["is_member_of", "is_observer_of", "is_cooperating_partner_of"];

/** Europe, framed from Iceland to Turkey; the United States and Egypt are panned to. */
const initialBounds: [[number, number], [number, number]] = [
	[34, -24],
	[71, 45],
];

/**
 * Fills per status, for the legend's swatches; the map's countries repeat them, see `CountriesMap`. A partner's stripes
 * are a gradient here and an svg pattern on the map, both 45°, 3px of member colour in every 8px.
 */
const swatchClassNames: Record<Status, string> = {
	is_member_of: "bg-background-map-member",
	is_observer_of: "bg-[color-mix(in_srgb,var(--color-background-map-member)_60%,var(--color-background-overlay))]",
	is_cooperating_partner_of:
		"bg-[repeating-linear-gradient(-45deg,var(--color-background-map-member)_0_3px,var(--color-background-map-partner)_3px_8px)]",
};

/**
 * The zoom buttons' icons, Lucide's `Plus` and `Minus`: Leaflet sets a button's content as an html string, so they are
 * written out rather than rendered from `lucide-react`.
 */
const zoomInIcon =
	'<svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/><path d="M12 5v14"/></svg>';
const zoomOutIcon =
	'<svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/></svg>';

/**
 * Class names for the zoom buttons, set on the map's element: two separate squares, like the legend and the list,
 * rather than Leaflet's joined, rounded bar. From `lg` up they are inset from the corner as far as the legend is;
 * below, the legend is not over the map, and they sit close to the corner, as far in as the page's gutter.
 */
const zoomControlClassNames = [
	"[&_.leaflet-bar]:flex [&_.leaflet-bar]:flex-col [&_.leaflet-bar]:gap-y-2 [&_.leaflet-bar]:rounded-none [&_.leaflet-bar]:border-0 [&_.leaflet-bar]:shadow-none [&_.leaflet-bar]:mbs-4 [&_.leaflet-bar]:me-4 lg:[&_.leaflet-bar]:mbs-6 lg:[&_.leaflet-bar]:me-10",
	"[&_.leaflet-bar_a]:flex [&_.leaflet-bar_a]:size-10 [&_.leaflet-bar_a]:items-center [&_.leaflet-bar_a]:justify-center [&_.leaflet-bar_a]:rounded-none [&_.leaflet-bar_a]:border-0 [&_.leaflet-bar_a]:bg-background-base [&_.leaflet-bar_a]:text-icon-accent [&_.leaflet-bar_a]:shadow-card-edge [&_.leaflet-bar_a]:hover:bg-background-accent [&_.leaflet-bar_a]:focus-visible-outline",
	"[&_.leaflet-bar_a.leaflet-disabled]:bg-background-base [&_.leaflet-bar_a.leaflet-disabled]:text-text-weak",
].join(" ");

/** The svg pattern which stripes a cooperating partner's country; one map per page, so a fixed id is unique. */
const partnerPatternId = "members-and-partners-map-partner";

/** Class names for the map's country paths: a status has underscores, which Tailwind reads as spaces in a selector. */
const countryClassNames: Record<Status, string> = {
	is_member_of: "country-member",
	is_observer_of: "country-observer",
	is_cooperating_partner_of: "country-partner",
};

/**
 * Class names for the map when the list is narrowed to a status: every other country is filled as one without a status,
 * and does not respond to the pointer, so it has no tooltip and cannot be clicked.
 */
const filterClassNames: Record<Status, string> = {
	is_member_of:
		"[&_.country:not(.country-member)]:pointer-events-none [&_.country:not(.country-member)]:fill-background-placeholder",
	is_observer_of:
		"[&_.country:not(.country-observer)]:pointer-events-none [&_.country:not(.country-observer)]:fill-background-placeholder",
	is_cooperating_partner_of:
		"[&_.country:not(.country-partner)]:pointer-events-none [&_.country:not(.country-partner)]:fill-background-placeholder",
};

export interface MembersAndPartnersMapItem {
	id: string;
	name: string;
	slug: string;
	status: Status;
	/** The number of the country's partner institutions, or of its cooperating partners for a cooperating partner. */
	institutionsCount: number;
}

interface MembersAndPartnersMapProps {
	items: Array<MembersAndPartnersMapItem>;
}

/**
 * The members and partners on a map of country outlines, without a tile layer, next to a list of the same countries,
 * which can be narrowed by status, and the map with it. The list is the map's accessible equivalent: every country on
 * the map links to its page from the list as well. Hovering a country on the map shows its name and status; clicking it
 * navigates to its page.
 *
 * Cooperating partner is not a country's status but that of institutions in it, so such a country is labelled with the
 * number of its cooperating partners rather than a status.
 *
 * Status is shown by colour alone on the map, not by a letter on each country: a letter needs the legend to be read,
 * and does not fit on a small country. The tooltip and the list name the status in words.
 *
 * Countries are matched to the Natural Earth outlines by name, against any of a country's names there - "Czech
 * Republic" is "Czechia" for short.
 */
export function MembersAndPartnersMap(props: Readonly<MembersAndPartnersMapProps>): ReactNode {
	const { items } = props;

	const t = useTranslations();

	function getStatusLabel(item: MembersAndPartnersMapItem): string {
		switch (item.status) {
			case "is_member_of": {
				return t("Member");
			}
			case "is_observer_of": {
				return t("Observer");
			}
			case "is_cooperating_partner_of": {
				return t("{count, plural, one {# cooperating partner} other {# cooperating partners}}", {
					count: item.institutionsCount,
				});
			}
		}
	}

	const legendLabels: Record<Status, string> = {
		is_member_of: t("Member country"),
		is_observer_of: t("Observer country"),
		is_cooperating_partner_of: t("Country with cooperating partners"),
	};

	const filterLabels: Record<Status, string> = {
		is_member_of: t("Members"),
		is_observer_of: t("Observers"),
		is_cooperating_partner_of: t("Cooperating partners"),
	};

	const presentStatuses = statuses.filter((status) => items.some((item) => item.status === status));

	const [filter, setFilter] = useState<Status | "all">("all");

	const visibleItems = filter === "all" ? items : items.filter((item) => item.status === filter);

	return (
		<div className="relative grid lg:block">
			<CountriesMap filter={filter} getStatusLabel={getStatusLabel} items={items} />
			<div className="flex flex-col bg-background-base shadow-card lg:absolute lg:inset-y-6 lg:inset-s-10 lg:inline-80">
				<Select
					className="m-4"
					label={t("Show")}
					onChange={setFilter}
					options={[
						{ id: "all", label: t("All countries") },
						...presentStatuses.map((status) => {
							return { id: status, label: filterLabels[status] };
						}),
					]}
					value={filter}
				/>
				{/**
				 * Indented by the select's margin and padding, so the names line up with the selected option's text. Below `lg` the
				 * list is part of the page rather than a scroll box of its own, which would catch the page's scrolling. The scroll box
				 * clips on both axes, so it reaches 5px up into the select's margin, with as much padding, to keep the first link's
				 * focus outline whole.
				 */}
				<ul
					className="flex flex-col gap-y-4 ps-8 pe-4 pbe-6 lg:-mbs-[5px] lg:flex-1 lg:overflow-y-auto lg:pbs-[5px] lg:focus-visible-outline lg:[--focus-outline-offset:-3px]"
					role="list"
				>
					{visibleItems.map((item) => (
						<li key={item.id} className="flex flex-col gap-y-1">
							<Link
								className="font-heading text-title-5 font-bold text-text-accent underline-offset-4 hover:underline focus-visible-outline"
								href={href({ pathname: "/network/members-and-partners/[slug]", params: { slug: item.slug } })}
								prefetch="intent"
							>
								{item.name}
							</Link>
							<span className="text-small">{getStatusLabel(item)}</span>
						</li>
					))}
				</ul>
			</div>
			<ul
				className="-order-1 flex flex-wrap gap-x-6 gap-y-2 bg-background-base px-4 py-3 shadow-card lg:absolute lg:inset-e-10 lg:inset-be-6"
				role="list"
			>
				{presentStatuses.map((status) => (
					<li key={status} className="flex items-center gap-x-2">
						<span aria-hidden={true} className={`${swatchClassNames[status]} size-4 shrink-0`} />
						{legendLabels[status]}
					</li>
				))}
			</ul>
		</div>
	);
}

interface CountriesMapProps {
	items: Array<MembersAndPartnersMapItem>;
	filter: Status | "all";
	getStatusLabel: (item: MembersAndPartnersMapItem) => string;
}

/**
 * Leaflet reads `window` when it is imported, so it is imported on the client only, after mount. Paths are styled with
 * class names rather than Leaflet's colour options, so the colours come from the design tokens: an SVG presentation
 * attribute cannot reference a css custom property, but a css rule overrides the attribute. Leaflet's own styles are in
 * a lower cascade layer (see `members-and-partners-map.css`), so utilities override them.
 *
 * From `lg` up the map is at least 32rem tall, so on a short screen the list over it still shows more than a handful of
 * countries.
 *
 * The filter is applied with class names too, so narrowing the list does not rebuild the map. They are set on a
 * wrapper: Leaflet adds its own class names to the map's element, which React would drop when it sets `className`.
 */
function CountriesMap(props: Readonly<CountriesMapProps>): ReactNode {
	const { items, filter, getStatusLabel } = props;

	const t = useTranslations();
	const router = useRouter();
	const elementRef = useRef<HTMLDivElement>(null);

	/**
	 * A country has no `Link` to prefetch its page while it is in the viewport, and its link in the list is mostly
	 * scrolled out of view, so it is prefetched on intent here, as a list link with `prefetch="intent"` is. A default
	 * `router.prefetch` loads only the route's App Shell, which the list's links have prefetched already; `kind: "full"`
	 * is what `<Link prefetch={true}>` uses, and the page sets `ensureStatic = "prefetch"`, so it is served from static
	 * output. `kind` is part of `router.prefetch`'s public type, though not of its documentation.
	 *
	 * A pointer moving over a country fires `pointerover` more than once, and each `router.prefetch` requests the page
	 * again, so a country is prefetched once, and again only after next reports the prefetch stale.
	 */
	const prefetchedRef = useRef(new Set<string>());
	const onIntent = useEffectEvent((item: MembersAndPartnersMapItem) => {
		const prefetched = prefetchedRef.current;

		if (prefetched.has(item.slug)) {
			return;
		}

		prefetched.add(item.slug);
		router.prefetch(href({ pathname: "/network/members-and-partners/[slug]", params: { slug: item.slug } }), {
			kind: fullPrefetch,
			onInvalidate() {
				prefetched.delete(item.slug);
			},
		});
	});
	const onSelect = useEffectEvent((item: MembersAndPartnersMapItem) => {
		router.push(href({ pathname: "/network/members-and-partners/[slug]", params: { slug: item.slug } }));
	});
	/** Read once when the map is created, so the map is not rebuilt when new props or labels come in. */
	const getOptions = useEffectEvent((): Omit<CreateMapOptions, "onIntent" | "onSelect"> => {
		return { items, getStatusLabel, zoomInTitle: t("Zoom in"), zoomOutTitle: t("Zoom out") };
	});

	useEffect(() => {
		const element = elementRef.current;

		if (element == null) {
			return;
		}

		const controller = new AbortController();
		let map: LeafletMap | null = null;

		void (async () => {
			try {
				const options = {
					...getOptions(),
					onIntent(item: MembersAndPartnersMapItem) {
						onIntent(item);
					},
					onSelect(item: MembersAndPartnersMapItem) {
						onSelect(item);
					},
				};
				const created = await createMap(element, options, controller.signal);

				if (controller.signal.aborted) {
					created.remove();
				} else {
					map = created;
				}
			} catch (error) {
				if (!controller.signal.aborted) {
					throw error;
				}
			}
		})();

		return () => {
			controller.abort();
			map?.remove();
		};
	}, []);

	return (
		<div className={filter !== "all" ? filterClassNames[filter] : undefined}>
			<div
				ref={elementRef}
				className={`${zoomControlClassNames} isolate block-96 bg-background-callout font-body lg:block-[clamp(32rem,85svh,56rem)] [&_.country]:fill-background-placeholder [&_.country]:stroke-stroke-inverse [&_.country-partner]:fill-[url(#members-and-partners-map-partner)] [&_.country-member]:fill-background-map-member [&_.country-observer]:fill-[color-mix(in_srgb,var(--color-background-map-member)_60%,var(--color-background-overlay))] [&_.country.leaflet-interactive]:hover:stroke-stroke-strong [&_.country.leaflet-interactive]:hover:[stroke-width:2]`}
			/>
		</div>
	);
}

interface CreateMapOptions {
	items: Array<MembersAndPartnersMapItem>;
	getStatusLabel: (item: MembersAndPartnersMapItem) => string;
	/** A pointer hovers a country, or a touch starts on it - the country may be selected next. */
	onIntent: (item: MembersAndPartnersMapItem) => void;
	onSelect: (item: MembersAndPartnersMapItem) => void;
	zoomInTitle: string;
	zoomOutTitle: string;
}

async function createMap(element: HTMLElement, options: CreateMapOptions, signal: AbortSignal): Promise<LeafletMap> {
	const { items, getStatusLabel, onIntent, onSelect, zoomInTitle, zoomOutTitle } = options;

	const [leaflet, response] = await Promise.all([import("leaflet"), fetch(countriesPathname, { signal })]);
	const countries = (await response.json()) as Countries;

	const itemsByName = new Map(items.map((item) => [item.name, item]));

	function findItem(country: CountryProperties): MembersAndPartnersMapItem | undefined {
		return country.names.map((name) => itemsByName.get(name)).find((item) => item != null);
	}

	const map = new leaflet.Map(element, {
		attributionControl: false,
		zoomControl: false,
		/** The page scrolls past the map; zooming is with the buttons, a pinch, or a double click. */
		scrollWheelZoom: false,
		minZoom: 2,
		maxZoom: 6,
		zoomSnap: 0.25,
		maxBounds: [
			[-85, -240],
			[85, 240],
		],
	});

	new leaflet.Control.Zoom({
		position: "topright",
		zoomInText: zoomInIcon,
		zoomInTitle,
		zoomOutText: zoomOutIcon,
		zoomOutTitle,
	}).addTo(map);

	/**
	 * One tooltip for all countries, opened only for a pointer which hovers. Bound to each country, Leaflet opens a
	 * country's tooltip on `pointerover` and on click, and closes it on `pointerout` - which a touch that pans the map
	 * does not fire, so tooltips opened while panning, and stayed open side by side. A tap navigates straight away, so it
	 * needs no tooltip.
	 */
	const tooltip = new leaflet.Tooltip({
		className:
			"rounded-none border-0 bg-background-base px-4 py-2.5 text-text-strong shadow-none drop-shadow-card-edge",
		direction: "top",
		offset: [0, -8],
	});

	new leaflet.GeoJSON<CountryProperties, Polygon | MultiPolygon>(countries, {
		style(feature) {
			const item = feature != null ? findItem(feature.properties) : undefined;

			return {
				className: item != null ? `country ${countryClassNames[item.status]}` : "country",
				interactive: item != null,
				weight: 1,
				fillOpacity: 1,
			};
		},
		onEachFeature(feature, layer) {
			const item = findItem(feature.properties);

			if (item == null) {
				return;
			}

			const content = createTooltip(item.name, getStatusLabel(item));

			/**
			 * Raised on hover, so its outline is drawn over its neighbours' rather than under them. Leaflet 2 fires pointer
			 * events, not mouse events. A touch fires `pointerover` too, as it starts - before the tap's `click` - so its
			 * page is prefetched then, as a link's is on `touchstart`.
			 */
			layer.on("pointerover", (event) => {
				onIntent(item);

				if (!isHovering(event)) {
					return;
				}

				(layer as Path).bringToFront();
				tooltip
					.setContent(content)
					.setLatLng((event as LeafletMouseEvent).latlng)
					.openOn(map);
			});
			layer.on("pointermove", (event) => {
				if (tooltip.isOpen() && isHovering(event)) {
					tooltip.setLatLng((event as LeafletMouseEvent).latlng);
				}
			});
			layer.on("pointerout", () => {
				tooltip.close();
			});
			layer.on("click", () => {
				onSelect(item);
			});
		},
	}).addTo(map);

	/** From `lg` up the list sits over the map's left side, so Europe is framed in the space to its right. */
	const isWide = window.matchMedia("(min-width: 64rem)").matches;
	map.fitBounds(initialBounds, { paddingTopLeft: [isWide ? 360 : 0, 0] });

	/** Leaflet creates the svg the countries are drawn into only once the map has a view. */
	addPartnerPattern(map.getPanes().overlayPane.querySelector("svg"));

	return map;
}

/** Whether a Leaflet pointer event comes from a pointer which hovers - a mouse or a pen - rather than a touch. */
function isHovering(event: LeafletEvent): boolean {
	const { originalEvent } = event as LeafletMouseEvent;

	return !(originalEvent instanceof PointerEvent && originalEvent.pointerType === "touch");
}

/** Built as elements rather than an html string: a name from the api is never parsed as markup. */
function createTooltip(name: string, status: string): HTMLElement {
	const content = document.createElement("span");
	content.className = "flex flex-col";

	const nameElement = document.createElement("span");
	nameElement.className = "font-heading text-body leading-heading font-bold text-text-accent";
	nameElement.textContent = name;

	const statusElement = document.createElement("span");
	statusElement.className = "text-small";
	statusElement.textContent = status;

	content.append(nameElement, statusElement);

	return content;
}

/**
 * Adds the stripes a cooperating partner's country is filled with to the svg Leaflet draws the countries into. Its
 * colours are set as inline styles, which unlike presentation attributes can use the css custom properties.
 */
function addPartnerPattern(svg: SVGSVGElement | null): void {
	if (svg == null) {
		return;
	}

	const namespace = "http://www.w3.org/2000/svg";

	const defs = document.createElementNS(namespace, "defs");
	const pattern = document.createElementNS(namespace, "pattern");
	pattern.id = partnerPatternId;
	pattern.setAttribute("patternUnits", "userSpaceOnUse");
	pattern.setAttribute("width", "8");
	pattern.setAttribute("height", "8");
	pattern.setAttribute("patternTransform", "rotate(45)");

	const background = document.createElementNS(namespace, "rect");
	background.setAttribute("width", "8");
	background.setAttribute("height", "8");
	background.setAttribute("style", "fill: var(--color-background-map-partner)");

	const stripe = document.createElementNS(namespace, "rect");
	stripe.setAttribute("width", "3");
	stripe.setAttribute("height", "8");
	stripe.setAttribute("style", "fill: var(--color-background-map-member)");

	pattern.append(background, stripe);
	defs.append(pattern);
	svg.prepend(defs);
}
