import * as path from "node:path";
import { fileURLToPath } from "node:url";

import { createUrl, createUrlSearchParams, log } from "@acdh-oeaw/lib";
import nextEnv from "@next/env";
import * as v from "valibot";

import { client } from "#/configs/env.schema.ts";

const projectDir = fileURLToPath(new URL("../..", import.meta.url));

/**
 * Like `scripts/openapi/generate.ts`, this runs in the `prepare` lifecycle script, before a local `.env.local` may
 * exist, so only the api base url is validated. The request is sent without the access token; a fresh clone needs one
 * or two requests, which is well within the api's rate limit.
 */
const { combinedEnv } = nextEnv.loadEnvConfig(projectDir);
const env = v.parse(v.object({ NEXT_PUBLIC_API_BASE_URL: client.entries.NEXT_PUBLIC_API_BASE_URL }), combinedEnv);

const outputFile = path.join(projectDir, "lib", "api", "page-slugs.ts");

const ResponseSchema = v.object({
	total: v.number(),
	data: v.array(v.object({ entity: v.object({ slug: v.string() }) })),
});

/** The maximum `limit` the api accepts, see `getPageSlugs.SearchParams` in the generated endpoints. */
const limit = 100;

async function fetchPageSlugs(): Promise<Array<string>> {
	const slugs: Array<string> = [];

	/** Each page's `total` decides whether another one is needed, so the requests are inherently sequential. */
	async function walk(offset: number): Promise<void> {
		const url = createUrl({
			baseUrl: env.NEXT_PUBLIC_API_BASE_URL,
			pathname: "/api/v1/pages/slugs",
			searchParams: createUrlSearchParams({ limit, offset }),
		});

		const response = await fetch(url);

		if (!response.ok) {
			throw new Error(`Failed to fetch page slugs from ${String(url)}: ${String(response.status)}.`);
		}

		const { data, total } = v.parse(ResponseSchema, await response.json());

		for (const { entity } of data) {
			slugs.push(entity.slug);
		}

		/** The second condition guards against an api which reports a `total` it never delivers. */
		if (offset + data.length >= total || data.length === 0) {
			return;
		}

		await walk(offset + data.length);
	}

	await walk(0);

	return slugs.toSorted();
}

/**
 * Emits the slugs of the pages which currently exist in the knowledge base as a string union, so a page route which
 * asks for a page that has been renamed or deleted fails the build with a type error, instead of shipping a 404. The
 * list is a snapshot taken when this script last ran, so consumers still handle a `null` page at request time.
 */
function emit(slugs: Array<string>): string {
	const lines = [
		"/** This file was generated by `scripts/pages/generate.ts`. Do not edit it by hand. */",
		"",
		"/** The slugs of the pages which existed in the knowledge base when the api client was last generated. */",
		"export const pageSlugs = [",
		...slugs.map((slug) => `\t${JSON.stringify(slug)},`),
		"] as const;",
		"",
		"export type PageSlug = (typeof pageSlugs)[number];",
		"",
	];

	return lines.join("\n");
}

async function generate(): Promise<void> {
	const slugs = await fetchPageSlugs();

	if (slugs.length === 0) {
		throw new Error("The api returned no page slugs.");
	}

	await Bun.write(outputFile, emit(slugs));
}

generate()
	// oxlint-disable-next-line promise/always-return
	.then(() => {
		log.success("Successfully generated page slugs.");
	})
	.catch((error: unknown) => {
		log.error("Failed to generate page slugs.\n", error);
		process.exitCode = 1;
	});
